// contract.css.ts
import { createThemeContract } from '@vanilla-extract/css';

export const themeContract = createThemeContract({
  palette: {
    mode: null,
    primary: {
      main: null,
      light: null,
      dark: null,
      contrastText: null,
    },
    secondary: {
      main: null,
      light: null,
      dark: null,
      contrastText: null,
    },
    error: {
      main: null,
      light: null,
      dark: null,
      contrastText: null,
    },
    warning: {
      main: null,
      light: null,
      dark: null,
      contrastText: null,
    },
    info: {
      main: null,
      light: null,
      dark: null,
      contrastText: null,
    },
    success: {
      main: null,
      light: null,
      dark: null,
      contrastText: null,
    },
    grey: {
      50: null,
      100: null,
      200: null,
      300: null,
      400: null,
      500: null,
      600: null,
      700: null,
      800: null,
      900: null,
      A100: null,
      A200: null,
      A400: null,
      A700: null,
    },
    text: {
      primary: null,
      secondary: null,
      disabled: null,
    },
    background: {
      default: null,
      paper: null,
    },
    action: {
      active: null,
      hover: null,
      selected: null,
      disabled: null,
      disabledBackground: null,
      focus: null,
    },
    divider: null,
  },
  typography: {
    fontFamily: null,
    fontSize: null,
    fontWeightLight: null,
    fontWeightRegular: null,
    fontWeightMedium: null,
    fontWeightBold: null,
    h1: {
      fontSize: null,
      fontWeight: null,
      lineHeight: null,
      letterSpacing: null,
    },
    h2: {
      fontSize: null,
      fontWeight: null,
      lineHeight: null,
      letterSpacing: null,
    },
    h3: {
      fontSize: null,
      fontWeight: null,
      lineHeight: null,
      letterSpacing: null,
    },
    h4: {
      fontSize: null,
      fontWeight: null,
      lineHeight: null,
      letterSpacing: null,
    },
    h5: {
      fontSize: null,
      fontWeight: null,
      lineHeight: null,
      letterSpacing: null,
    },
    h6: {
      fontSize: null,
      fontWeight: null,
      lineHeight: null,
      letterSpacing: null,
    },
    subtitle1: {
      fontSize: null,
      fontWeight: null,
      lineHeight: null,
      letterSpacing: null,
    },
    subtitle2: {
      fontSize: null,
      fontWeight: null,
      lineHeight: null,
      letterSpacing: null,
    },
    body1: {
      fontSize: null,
      fontWeight: null,
      lineHeight: null,
      letterSpacing: null,
    },
    body2: {
      fontSize: null,
      fontWeight: null,
      lineHeight: null,
      letterSpacing: null,
    },
    button: {
      fontSize: null,
      fontWeight: null,
      lineHeight: null,
      letterSpacing: null,
      textTransform: null,
    },
    caption: {
      fontSize: null,
      fontWeight: null,
      lineHeight: null,
      letterSpacing: null,
    },
    overline: {
      fontSize: null,
      fontWeight: null,
      lineHeight: null,
      letterSpacing: null,
      textTransform: null,
    },
  },
  spacing: {
    unit: null,
    xs: null,
    sm: null,
    md: null,
    lg: null,
    xl: null,
    xxl: null,
  },
  breakpoints: {
    xs: null,
    sm: null,
    md: null,
    lg: null,
    xl: null,
  },
  zIndex: {
    mobileStepper: null,
    fab: null,
    speedDial: null,
    appBar: null,
    drawer: null,
    modal: null,
    snackbar: null,
    tooltip: null,
  },
  transitions: {
    easing: {
      easeInOut: null,
      easeOut: null,
      easeIn: null,
      sharp: null,
    },
    duration: {
      shortest: null,
      shorter: null,
      short: null,
      standard: null,
      complex: null,
      enteringScreen: null,
      leavingScreen: null,
    },
  },
  shadows: {
    0: null,
    1: null,
    2: null,
    3: null,
    4: null,
    5: null,
    6: null,
    7: null,
    8: null,
    9: null,
    10: null,
    11: null,
    12: null,
    13: null,
    14: null,
    15: null,
    16: null,
    17: null,
    18: null,
    19: null,
    20: null,
    21: null,
    22: null,
    23: null,
    24: null,
  },
  shape: {
    borderRadius: null,
  },
});
