import { InitColorSchemeScript } from '@mui/material';
import { EnhancedThemeProvider, enhancedThemes } from '@jc/themes';

// import { availableThemes } from '@/themes';

import 'augmented-ui/augmented-ui.min.css';
import './global.css';

export const metadata = {
  title: 'Welcome to portfolio-site',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* Prevent SSR color scheme flicker */}
        {/* <InitColorSchemeScript defaultMode="system" /> */}
        <EnhancedThemeProvider
          themes={enhancedThemes}
          defaultThemeId="neon-cyberpunk"
          defaultColorMode="system"
          themeStorageKey="my-app-theme"
          colorModeStorageKey="my-app-color-mode"
        >
          {children}
        </EnhancedThemeProvider>
      </body>
    </html>
  );
}
