import { ThemeContextProvider } from '@jc/themes';

import { availableThemes } from '@/themes';

import 'augmented-ui/augmented-ui.min.css';
import './global.css';

export const metadata = {
  title: 'Welcome to portfolio-site',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeContextProvider
          themes={availableThemes}
          defaultThemeId="neon-cyberpunk"
          storageKey="my-app-theme"
        >
          {children}
        </ThemeContextProvider>
      </body>
    </html>
  );
}
