export const InfoTheme = {
  solid: {
    background: {
      default: { backgroundColor: '$info' },
      hover: { backgroundColor: '$info', filter: 'brightness(1.1)' },
      focus: { backgroundColor: '$info', filter: 'brightness(1.1)' },
      active: { backgroundColor: '$info', filter: 'brightness(0.9)' },
      disabled: { backgroundColor: '$surface' },
    },
    border: {
      default: { stroke: '$info' },
      hover: { stroke: '$info' },
      focus: { stroke: '$info' },
      active: { stroke: '$info' },
      disabled: { stroke: '$borderMuted' },
    },
    content: {
      default: { color: '$textOnPrimary', fontWeight: '$medium' },
      hover: { color: '$textOnPrimary' },
      focus: { color: '$textOnPrimary' },
      active: { color: '$textOnPrimary' },
      disabled: { color: '$textMuted' },
    },
    shadow: {
      default: { filter: 'drop-shadow(0 2px 4px rgba(0, 0, 0, 0.1))' },
      hover: { filter: 'drop-shadow(0 4px 8px rgba(0, 0, 0, 0.15))' },
      focus: { filter: 'drop-shadow(0 4px 8px rgba(0, 0, 0, 0.15))' },
      active: { filter: 'drop-shadow(0 1px 2px rgba(0, 0, 0, 0.1))' },
      disabled: { filter: 'none' },
    },
  },
  outline: {
    background: {
      default: { backgroundColor: 'transparent' },
      hover: { backgroundColor: '$info', opacity: 0.1 },
      focus: { backgroundColor: '$info', opacity: 0.1 },
      active: { backgroundColor: '$info', opacity: 0.2 },
      disabled: { backgroundColor: 'transparent' },
    },
    border: {
      default: { stroke: '$info', strokeWidth: '2px' },
      hover: { stroke: '$info', strokeWidth: '2px' },
      focus: { stroke: '$info', strokeWidth: '2px' },
      active: { stroke: '$info', strokeWidth: '2px' },
      disabled: { stroke: '$borderMuted', strokeWidth: '2px' },
    },
    content: {
      default: { color: '$info', fontWeight: '$medium' },
      hover: { color: '$info' },
      focus: { color: '$info' },
      active: { color: '$info' },
      disabled: { color: '$textMuted' },
    },
    shadow: {
      default: { filter: 'none' },
      hover: { filter: 'drop-shadow(0 2px 4px rgba(0, 0, 0, 0.1))' },
      focus: { filter: 'drop-shadow(0 2px 4px rgba(0, 0, 0, 0.1))' },
      active: { filter: 'none' },
      disabled: { filter: 'none' },
    },
  },
  ghost: {
    background: {
      default: { backgroundColor: 'transparent' },
      hover: { backgroundColor: '$info', opacity: 0.1 },
      focus: { backgroundColor: '$info', opacity: 0.1 },
      active: { backgroundColor: '$info', opacity: 0.15 },
      disabled: { backgroundColor: 'transparent' },
    },
    border: {
      default: { stroke: 'transparent', strokeWidth: '0px' },
      hover: { stroke: 'transparent', strokeWidth: '0px' },
      focus: { stroke: '$info', strokeWidth: '1px' },
      active: { stroke: 'transparent', strokeWidth: '0px' },
      disabled: { stroke: 'transparent', strokeWidth: '0px' },
    },
    content: {
      default: { color: '$info', fontWeight: '$medium' },
      hover: { color: '$info' },
      focus: { color: '$info' },
      active: { color: '$info' },
      disabled: { color: '$textMuted' },
    },
    shadow: {
      default: { filter: 'none' },
      hover: { filter: 'none' },
      focus: { filter: 'none' },
      active: { filter: 'none' },
      disabled: { filter: 'none' },
    },
  },
  soft: {
    background: {
      default: { backgroundColor: '$info', opacity: 0.1 },
      hover: { backgroundColor: '$info', opacity: 0.15 },
      focus: { backgroundColor: '$info', opacity: 0.15 },
      active: { backgroundColor: '$info', opacity: 0.2 },
      disabled: { backgroundColor: '$surface', opacity: 0.5 },
    },
    border: {
      default: { stroke: 'transparent', strokeWidth: '0px' },
      hover: { stroke: 'transparent', strokeWidth: '0px' },
      focus: { stroke: '$info', strokeWidth: '1px' },
      active: { stroke: 'transparent', strokeWidth: '0px' },
      disabled: { stroke: 'transparent', strokeWidth: '0px' },
    },
    content: {
      default: { color: '$info', fontWeight: '$medium' },
      hover: { color: '$info' },
      focus: { color: '$info' },
      active: { color: '$info' },
      disabled: { color: '$textMuted' },
    },
    shadow: {
      default: { filter: 'none' },
      hover: { filter: 'drop-shadow(0 2px 4px rgba(0, 0, 0, 0.1))' },
      focus: { filter: 'drop-shadow(0 2px 4px rgba(0, 0, 0, 0.1))' },
      active: { filter: 'none' },
      disabled: { filter: 'none' },
    },
  },
};
