export const SecondaryTheme = {
  solid: {
    background: {
      default: { backgroundColor: '$secondary' },
      hover: { backgroundColor: '$secondaryHover' },
      focus: { backgroundColor: '$secondaryHover' },
      active: { backgroundColor: '$secondaryActive' },
      disabled: { backgroundColor: '$surface' },
    },
    border: {
      default: { stroke: '$secondary' },
      hover: { stroke: '$secondaryHover' },
      focus: { stroke: '$secondaryHover' },
      active: { stroke: '$secondaryActive' },
      disabled: { stroke: '$borderMuted' },
    },
    content: {
      default: { color: '$textPrimary', fontWeight: '$medium' },
      hover: { color: '$textPrimary' },
      focus: { color: '$textPrimary' },
      active: { color: '$textPrimary' },
      disabled: { color: '$textMuted' },
    },
    shadow: {
      default: { filter: 'drop-shadow(0 2px 4px rgba(0, 0, 0, 0.1))' },
      hover: { filter: 'drop-shadow(0 4px 8px rgba(0, 0, 0, 0.15))' },
      focus: { filter: 'drop-shadow(0 4px 8px rgba(0, 0, 0, 0.15))' },
      active: { filter: 'drop-shadow(0 1px 2px rgba(0, 0, 0, 0.1))' },
      disabled: { filter: 'none' },
    },
  },
  outline: {
    background: {
      default: { backgroundColor: 'transparent' },
      hover: { backgroundColor: '$secondary', opacity: 0.1 },
      focus: { backgroundColor: '$secondary', opacity: 0.1 },
      active: { backgroundColor: '$secondary', opacity: 0.2 },
      disabled: { backgroundColor: 'transparent' },
    },
    border: {
      default: { stroke: '$secondary', strokeWidth: '2px' },
      hover: { stroke: '$secondaryHover', strokeWidth: '2px' },
      focus: { stroke: '$secondaryHover', strokeWidth: '2px' },
      active: { stroke: '$secondaryActive', strokeWidth: '2px' },
      disabled: { stroke: '$borderMuted', strokeWidth: '2px' },
    },
    content: {
      default: { color: '$secondary', fontWeight: '$medium' },
      hover: { color: '$secondaryHover' },
      focus: { color: '$secondaryHover' },
      active: { color: '$secondaryActive' },
      disabled: { color: '$textMuted' },
    },
    shadow: {
      default: { filter: 'none' },
      hover: { filter: 'drop-shadow(0 2px 4px rgba(0, 0, 0, 0.1))' },
      focus: { filter: 'drop-shadow(0 2px 4px rgba(0, 0, 0, 0.1))' },
      active: { filter: 'none' },
      disabled: { filter: 'none' },
    },
  },
  ghost: {
    background: {
      default: { backgroundColor: 'transparent' },
      hover: { backgroundColor: '$secondary', opacity: 0.1 },
      focus: { backgroundColor: '$secondary', opacity: 0.1 },
      active: { backgroundColor: '$secondary', opacity: 0.15 },
      disabled: { backgroundColor: 'transparent' },
    },
    border: {
      default: { stroke: 'transparent', strokeWidth: '0px' },
      hover: { stroke: 'transparent', strokeWidth: '0px' },
      focus: { stroke: '$secondary', strokeWidth: '1px' },
      active: { stroke: 'transparent', strokeWidth: '0px' },
      disabled: { stroke: 'transparent', strokeWidth: '0px' },
    },
    content: {
      default: { color: '$secondary', fontWeight: '$medium' },
      hover: { color: '$secondaryHover' },
      focus: { color: '$secondaryHover' },
      active: { color: '$secondaryActive' },
      disabled: { color: '$textMuted' },
    },
    shadow: {
      default: { filter: 'none' },
      hover: { filter: 'none' },
      focus: { filter: 'none' },
      active: { filter: 'none' },
      disabled: { filter: 'none' },
    },
  },
  soft: {
    background: {
      default: { backgroundColor: '$secondary', opacity: 0.1 },
      hover: { backgroundColor: '$secondary', opacity: 0.15 },
      focus: { backgroundColor: '$secondary', opacity: 0.15 },
      active: { backgroundColor: '$secondary', opacity: 0.2 },
      disabled: { backgroundColor: '$surface', opacity: 0.5 },
    },
    border: {
      default: { stroke: 'transparent', strokeWidth: '0px' },
      hover: { stroke: 'transparent', strokeWidth: '0px' },
      focus: { stroke: '$secondary', strokeWidth: '1px' },
      active: { stroke: 'transparent', strokeWidth: '0px' },
      disabled: { stroke: 'transparent', strokeWidth: '0px' },
    },
    content: {
      default: { color: '$secondary', fontWeight: '$medium' },
      hover: { color: '$secondaryHover' },
      focus: { color: '$secondaryHover' },
      active: { color: '$secondaryActive' },
      disabled: { color: '$textMuted' },
    },
    shadow: {
      default: { filter: 'none' },
      hover: { filter: 'drop-shadow(0 2px 4px rgba(0, 0, 0, 0.1))' },
      focus: { filter: 'drop-shadow(0 2px 4px rgba(0, 0, 0, 0.1))' },
      active: { filter: 'none' },
      disabled: { filter: 'none' },
    },
  },
};
